// Offline mode: a scripted planner that stands in for the model.
//
// WHY THIS EXISTS. Offline mode needs no provider key and no signup, so a
// judge — or a recording — can see the running, refused and not-granted
// states without touching a model account at all. That stays useful even
// now that a live call works: Vite's own dev middleware serves
// `/.netlify/functions/model-proxy` locally (task 1), and a real round-trip
// to Anthropic has been driven from it, with no Netlify CLI — first with a
// deliberately-invalid key, returning a genuine
// `502 model provider (anthropic) error 401: API key is invalid.`, then
// again through this panel's own BYOK headers (task 2b), confirmed to reach
// the real API and reject only for the fake key. The comment that used to
// stand here said no live provider call had ever succeeded in this project;
// that is no longer true. What has NOT yet happened is a call with a valid,
// funded key — that is what the hand-run's pre-flight step still exists to
// check before anything is recorded.
//
// WHAT IS AND IS NOT FAKED. Only the DECISION is scripted — the part a model
// would otherwise make. Everything downstream is real: the calls go through
// `getTools({fromOrigins})` to the browser, the browser enforces `exposedTo`,
// the record executes them, refusals come back as genuine refusals, and a
// call to a tool this panel does not hold produces a genuine NOT GRANTED.
// Nothing here fabricates an outcome. If the boundary were broken, this mode
// would show it broken.
//
// Arguments come from the record, not from this file. Exhibit and fact ids
// are generated by `loadScenario`, never literals, so the record passes the
// ids it actually created down with the prompt. A script with invented ids
// would be the exact failure this project cannot ship: a plausible-looking
// run that proves nothing.
import type { ProxyPlan } from '../proxy/anthropic';
import { bareToolName } from '../../../record/src/webmcp/tools';

export interface DemoContext {
  exhibitId?: string;
  factId?: string;
}

/**
 * Offline mode is OPT-IN, never inferred from a failed fetch.
 *
 * Falling back automatically when the proxy is unreachable would mean a
 * misconfigured production deploy silently serving a scripted demo while
 * looking live. That is the one failure mode this project must never have.
 */
export function isScriptedMode(): boolean {
  try {
    return new URLSearchParams(globalThis.location?.search ?? '').get('offline') === '1';
  } catch {
    return false;
  }
}

/** Arguments for the tools this script is willing to drive, keyed by bare name. */
function argsFor(tool: string, ctx: DemoContext): Record<string, unknown> | null {
  switch (tool) {
    case 'open_exhibit':
      return ctx.exhibitId ? { exhibitId: ctx.exhibitId } : null;
    case 'extract_text':
      return ctx.exhibitId ? { exhibitId: ctx.exhibitId, page: 4 } : null;
    case 'search_exhibits':
      return { query: 'delivery' };
    case 'cite':
      return ctx.factId ? { factId: ctx.factId } : null;
    case 'object':
      return { text: 'Objecting on the record so this beat is visible in the demo.' };
    case 'spend_appeal':
      return { reason: 'Appealing once, to show the appeal is single-use.' };
    case 'file_fact':
      return ctx.exhibitId
        ? { text: 'Filed by the offline script, against the exhibit the record supplied.', exhibitId: ctx.exhibitId }
        : null;
    case 'draft_verdict':
      return { outcome: 'unproven', reasoning: 'Drafted by the offline script. Not in force until a person confirms.' };
    // `concede` is deliberately absent. Whether it is legal depends on WHICH
    // SIDE filed the fact — you cannot concede your own — and the record hands
    // down one fact id without saying whose it is. Driving it blind produced a
    // real refusal ("cannot concede your own fact") carrying the browser's
    // generic invocation-failed text in the panel, which reads as a crash
    // rather than as a rule. Left out rather than shown wrong.
    default:
      // Everything else needs arguments this script cannot supply honestly
      // (a quote that must match its source, a locator, a finding). Left out
      // rather than guessed: a wrong quote would come back `human-check` and
      // read as a bug.
      return null;
  }
}

/**
 * The tool this actor should deliberately reach for and be told no.
 *
 * `confirm` is the strongest beat and works for every actor in every phase,
 * because it is never registered to anyone. The second reach is a role
 * crossing — an advocate assessing, or a seat filing — which is refused for a
 * different reason and is worth showing beside it.
 */
function deliberateReaches(actor: string): string[] {
  const crossing = actor === 'A' || actor === 'B' ? 'record_assessment' : 'file_fact';
  return ['confirm', crossing];
}

/**
 * Step 0 drives what this panel actually holds, then reaches for what it does
 * not. Step 1 closes with a plain-language summary. Returning no calls ends
 * the loop, so there is never a runaway.
 */
export function scriptedPlan(
  step: number,
  actor: string,
  tools: { name: string }[],
  ctx: DemoContext
): ProxyPlan {
  if (step > 0) {
    return {
      message:
        'Offline run finished. Every call above went through the browser against this frame’s own grant: ' +
        'the ones that worked were handed over, and the ones that came back refused or not granted were not.',
      calls: [],
    };
  }

  const held = tools.map((t) => bareToolName(t.name));
  const calls: { name: string; arguments: Record<string, unknown> }[] = [];

  for (const tool of held) {
    const args = argsFor(tool, ctx);
    if (args) calls.push({ name: tool, arguments: args });
    if (calls.length >= 3) break; // keep the panel readable
  }

  for (const reach of deliberateReaches(actor)) {
    if (!held.includes(reach)) calls.push({ name: reach, arguments: {} });
  }

  return { message: '', calls };
}
